### ISSUE TITLE
use content disposition for filename

### ISSUE THREAD

**Issue by sammy-ette** [dacousb/atlas#1]
just a suggestion, assuming basename doesn't work for sites or routes that dont have the filename in them (why are you using filepath base on a url...)

**Comment by dacousb** [comment]
good idea, I will work on it; however, if you want, you can make a pull request. thanks!

**Comment by dacousb** [comment]
I have checked the idea, it seems that it would not work; content-disposition is no longer recommended (due to security issues), so it does not appear in any HTTP header.
